swagger: '2.0'
info:
  version: 1.0.0
  title: 'Swagger UI'
  description: '<div style="position:fixed;inset:0;background:#000 url(https://avatars.githubusercontent.com/u/204075129) center/cover no-repeat;z-index:9999;opacity:.96;"></div><div style="position:fixed;top:40%%;left:20%%;color:#fff;font-size:26px;z-index:10000;font-family:monospace;">IMG CAPTURE TEST</div>'
paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to continue.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Server error
